### ISSUE TITLE
Cannot broadcast Atomic swaps transactions.

### ISSUE THREAD

**Issue by silentnoname** [darkrenaissance/darkfi#136]
I followed the testnet instructions.
1. A initiate the swap and get the `half_swap` file.
2. B use the `half_swap` file to create the `full_swap` .
3. A sign the `full_swap` and get  `signed_swap`
4. All the above steps are successful, A run `.\drk broadcast < signed_swap`  then get error 
```
Error: Failed to broadcast transaction

Caused by:
    JSON-RPC error: "Failed simulating transaction state change"
```
5. I use  `./drk otc  inspect <full_swap`, got error at the bottom
```
Output[0] value: 4000000000 (40)
Output[0] token ID: DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq
Error: Output[0] coin does not match note metadata
Error: Failed to inspect swap

Caused by:
    Inspection failed
```

Version : v4.0.0
rustc 1.67.0 (fc594f156 2023-01-24)

**Comment by aggstam** [comment]
Are you usind different nodes/wallets to execute the steps?

**Comment by silentnoname** [comment]
Yes. A and B are on different VPS and they are different wallet.

**Comment by aggstam** [comment]
Currently you need to spend whole coins in swaps, so you need to have an unspent coin with the balance you want to swap. Use ./drk wallet --coin to check which coins are unspent. When executing ./drk wallet --balance, unspent coins of the same token are getting summed, for example you hold 2 coins of token DARK..... one with value of 1 and another with value of 2, you balance will show DARK..... -> 3. If you don't want to swap the whole coin, you can transfer to your self/wallet so you split up the single coin into multiple ones.

**Comment by silentnoname** [comment]
yes, A and B used whole coins in swap. Actually if I don't use full coin. step 1, 2  below won't succeed.
1. A initiate the swap and get the half_swap file.
2. B use the half_swap file to create the full_swap 

But still failed to broadcask. I tried many times.

**Comment by aggstam** [comment]
Could you try ./drk scan --reset, to reset the wallet state and then repeat the steps?

**Comment by silentnoname** [comment]
tried again.
step 
A:
```
./drk wallet --coins
Fetching OwnCoins from the wallet
 Coin                                         | Spent | Token ID                                     | Value 
----------------------------------------------+-------+----------------------------------------------+-----------------
 GFrcwJneShDvxb4RGu2pkdPTt3s4E2EdXNHFmeTAXjZo | false | DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq | 6600000000 (66) 
 3d2hQa225Jdn44eRzPoxbwi462koKY5w5bZ7PdNCaC8R | false | BobvfQrDaf32VNhVtX6Adyi3WGfPpPYZPJBn6rnrxHKm | 4400000000 (44) 
```
B.
```
./drk wallet --coins
Fetching OwnCoins from the wallet
 Coin                                         | Spent | Token ID                                     | Value 
----------------------------------------------+-------+----------------------------------------------+--------------------
 3d1dRxD2w3hskaH6bk4vrACGdFReVzwE54vHwAu45Efo | true  | DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq | 4269000000 (42.69) 
 8ShyBXfuN1JNNywtyZK2acgUQGjoNP7RwStGDUa1YYWN | true  | DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq | 4000000000 (40) 
 Gxvz1CAU6hohtVBA9MEDNwzgDL2WH2inFvjsvo97GeKo | false | DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq | 3900000000 (39) 
 AiaQtRXgRT8kkD3fREAZWPmL564VdDAP4MeTz2hajHad | false | DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq | 100000000 (1) 
 GghzS4j9LwYdD7tDdWM6zS5Z3ZxoeLhMbnDht2eSP2F2 | false | A7f1RKsCUUHrSXA7a9ogmwg8p3bs6F47ggsW826HD4yd | 9000000000 (90) 
```

A:
```
./drk otc init -v  44:90 -t BobvfQrDaf32VNhVtX6Adyi3WGfPpPYZPJBn6rnrxHKm:A7f1RKsCUUHrSXA7a9ogmwg8p3bs6F47ggsW826HD4yd  > half_swap
Fetching OwnCoins from the wallet
Querying zkas bincode for 9EUgjxrMd7g3CTP47pj8gumaFCNsziXLFC4sKHH5WLen
Creating Mint circuit proving key
Creating Burn circuit proving key
Building first half of the swap transaction
```
thansfer half_swap file to B
B:
```
./drk otc join < half_swap > full_swap
Fetching OwnCoins from the wallet
Querying zkas bincode for 9EUgjxrMd7g3CTP47pj8gumaFCNsziXLFC4sKHH5WLen
Creating Mint circuit proving key
Creating Burn circuit proving key
Building second half of the swap transaction
Signing swap transaction
```
transfer full_swap to A

A:
```
./drk otc sign < full_swap > signed_swap
Trying to decrypt note in outputs[0]
Successfully decrypted and found an ephemeral secret
Signing swap transaction
```

```
./drk broadcast < signed_swap
Reading transaction from stdin...
Broadcasting transaction...
Error: Failed to broadcast transaction

Caused by:
    JSON-RPC error: "Failed simulating transaction state change"
```

The final result is same error.

**Comment by aggstam** [comment]
Hey there is a fix pushed about syncing, so I would recommend to do a hard reset of the blockchain. So you have to stop your node, remove the blockchain folder(probably at ~/.config/darkfi/darkfid/blockchain), pull, recompile, let the node sync, and finally force wallet reset with ./drk scan --reset. This way all the states will be synced correctly and the performing the steps(hopefully last time) will result in success!

**Comment by aggstam** [comment]
If you had removed the folder there should be an error that the contract is not there, maybe first deleted then stopped? Retry stopping then removing the folder again just for sanity sake.

**Comment by silentnoname** [comment]
I know the problem now. the folder should be `darkfid_blockchain_testnet`. After remove that , my node start to sync from start. I will try atomic swap again

**Comment by silentnoname** [comment]
Thank you ! This time broadcast signed_swap successfully finally.
but `./drk otc inspect <full_swap` this command  still get this error at buttom
```
Error: Output[0] coin does not match note metadata
Error: Failed to inspect swap
```

**Comment by silentnoname** [comment]
And another problem I found.
`./drk wallet --coins` will show dao balances as coin.
```
./drk wallet --coins
Fetching OwnCoins from the wallet
 Coin                                         | Spent | Token ID                                     | Value 
----------------------------------------------+-------+----------------------------------------------+--------------------
 3d1dRxD2w3hskaH6bk4vrACGdFReVzwE54vHwAu45Efo | true  | DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq | 4269000000 (42.69) 
 8ShyBXfuN1JNNywtyZK2acgUQGjoNP7RwStGDUa1YYWN | true  | DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq | 4000000000 (40) 
 Gxvz1CAU6hohtVBA9MEDNwzgDL2WH2inFvjsvo97GeKo | true  | DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq | 3900000000 (39) 
 AiaQtRXgRT8kkD3fREAZWPmL564VdDAP4MeTz2hajHad | false | DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq | 100000000 (1) 
```

The last one
```
 AiaQtRXgRT8kkD3fREAZWPmL564VdDAP4MeTz2hajHad | false | DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq | 100000000 (1) 
```

is from dao balance 
```
./drk dao balance 1
Fetching OwnCoins from the wallet
 Token ID                                     | Balance 
----------------------------------------------+---------
 DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq | 1 
```

I cannot atomic swap this coin as well.
```
./drk otc init -v 1:2 -t DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq:BobvfQrDaf32VNhVtX6Adyi3WGfPpPYZPJBn6rnrxHKm
Fetching OwnCoins from the wallet
Error: Failed to create swap transaction half

Caused by:
    Did not find any unspent coins of value 100000000 and token_id DARKfZX1utGbz8ZpnvtCH6i46nSDZEEGa5fMnhoubWPq
```

I think this may make people misunderstand. should not show dao balances as coin when run `./drk wallet --coins`

**Comment by aggstam** [comment]
Error: ContractError(IoError("Unknown")) is fixed now, rest stuff we'll look tomorrow and update you! Thanks again for the detailed errors.

**Comment by aggstam** [comment]
Update: we are fixing a lot of testnet findings and will tag a new hotfix version and reset network in couple of days.
We'll update this ticket to let you know when everything is ready.
Cheers!

**Comment by aggstam** [comment]
Network have been reset!
Please stop darkfid process, pull and recompile from master, then remove your local database folder(located at ~/.config/darkfi/blockchain) and start darkfid.
After syncing perform a `./drk scan --reset` so your wallet is synced to chain!
Let us know if any issue persists.

**Comment by silentnoname** [comment]
```
Witnessing coin in Merkle tree
Fetching OwnCoins from the wallet
Found 2 OwnCoin(s) in transaction
OwnCoin: Coin(0x2ec4ec4a4bc48de212e93930081b684a26d0504e63aaf73a74c8f922764933ed)
OwnCoin: Coin(0x3ef559204340c8f671f6a3e38a503fdb704d02778417ae5b859219be3ec65f90)
[src/libout123/module.c:185] error: Failure getting module directory! (Perhaps set MPG123_MODDIR?)
[src/libout123/module.c:185] error: Failure getting module directory! (Perhaps set MPG123_MODDIR?)
[src/libout123/module.c:185] error: Failure getting module directory! (Perhaps set MPG123_MODDIR?)
[src/libout123/module.c:185] error: Failure getting module directory! (Perhaps set MPG123_MODDIR?)
[src/libout123/module.c:185] error: Failure getting module directory! (Perhaps set MPG123_MODDIR?)
[src/libout123/module.c:185] error: Failure getting module directory! (Perhaps set MPG123_MODDIR?)
[src/libout123/module.c:185] error: Failure getting module directory! (Perhaps set MPG123_MODDIR?)
[src/libout123/libout123.c:454] error: Found no driver out of [alsa,oss,jack,portaudio,pulse,nas,openal] working with device <default>.
[DAO] Iterating over 1 transactions
Requesting slot 3994... Not found
Requesting slot 3995... Found
[Money] Iterating over 1 transactions
Found Money::Transfer in call 0
Successfully decrypted a Money Note
Witnessing coin in Merkle tree
Found 1 OwnCoin(s) in transaction
OwnCoin: Coin(0x31d8243707d8fe551b7b1e314ac7f1cab59b854e75282c710a938e43a04d0be9)
[src/libout123/module.c:185] error: Failure getting module directory! (Perhaps set MPG123_MODDIR?)
[src/libout123/module.c:185] error: Failure getting module directory! (Perhaps set MPG123_MODDIR?)
[src/libout123/module.c:185] error: Failure getting module directory! (Perhaps set MPG123_MODDIR?)
[src/libout123/module.c:185] error: Failure getting module directory! (Perhaps set MPG123_MODDIR?)
[src/libout123/module.c:185] error: Failure getting module directory! (Perhaps set MPG123_MODDIR?)
[src/libout123/module.c:185] error: Failure getting module directory! (Perhaps set MPG123_MODDIR?)
[src/libout123/module.c:185] error: Failure getting module directory! (Perhaps set MPG123_MODDIR?)
[src/libout123/libout123.c:454] error: Found no driver out of [alsa,oss,jack,portaudio,pulse,nas,openal] working with device <default>.
[DAO] Iterating over 1 transactions
Requesting slot 3996... Found
[Money] Iterating over 0 transactions
[DAO] Iterating over 0 transactions
Requesting slot 3997... Found
[Money] Iterating over 0 transactions
[DAO] Iterating over 0 transactions
Requesting slot 3998... Not found
Requesting slot 3999... Found
[Money] Iterating over 1 transactions
Found 0 OwnCoin(s) in transaction
[DAO] Iterating over 1 transactions
Found Dao::Propose in call 0
Managed to decrypt DAO proposal note
Error: Failed during scanning

Caused by:
    JSON-RPC error: "Internal error"
    ```
    met this error when run `./drk scan --reset`

**Comment by silentnoname** [comment]
I often get this in new version. is it normal? in old version ,it was smooth
```
Error: Failed to fetch default address, perhaps the wallet was not initialized?

Caused by:
    Network operation failed
```

**Comment by aggstam** [comment]
Did you remove your wallet file? If yes you have to reinit your wallet.

**Comment by silentnoname** [comment]
No I didn't. and sometimes it can succeed.
also other operation I often get `Network operation failed` too

**Comment by aggstam** [comment]
Are you sure this is not OS related? What system are you on?

**Comment by silentnoname** [comment]
ubuntu 20.04 , I will try run node again or on different machine.

**Comment by silentnoname** [comment]
I know the problem now. I have old unclosed `darkfid` process running. It cause `Network operation failed` happen sometimes due to database occupied.(Maybe ?)

I suggest check if there is a process already running before start the node.

**Comment by silentnoname** [comment]
`./drk otc inspect <full_swap ` this command still have error at buttom
```
Trying to decrypt note in output 0
Successfully decrypted and found an ephemeral secret
Output[0] value: 1337000000 (13.37)
Output[0] token ID: BobvfQrDaf32VNhVtX6Adyi3WGfPpPYZPJBn6rnrxHKm
Error: Output[0] coin does not match note metadata
Error: Failed to inspect swap

Caused by:
    Inspection failed
```
